app:
  name: "casino-transaction-service"
  version: "1.0.0"

http:
  port: "8080"
  read_header_timeout_seconds: 5
  read_timeout_seconds: 10
  write_timeout_seconds: 15
  idle_timeout_seconds: 60

logger:
  log_level: "debug"

postgres:
  pool_max_open: 25
  pool_max_idle: 5
  conn_max_lifetime_minutes: 5
  url: "postgres://postgres:pass@localhost:5432/casino?sslmode=disable"

kafka:
  brokers: ["localhost:9094"] # Using external port 9094 for local development outside Docker
  topic: "transactions"
  group_id: "processor-group"
  max_process_retries: 3
  dlq_topic: "transactions.dlq"
  metrics_flush_sec: 15
